# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clover and Rye	
email: info@cloverandrye.com
description: Clover and Rye is a company built to meet your graphic and web design needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cloverandrye.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

keep_files: [portfolio/_site/index.html]
keep_files: [portfolio/_site/portfolio/index.html]
keep_files: [portfolio/_site/css/main.css]
keep_files: [portfolio/_site/about/index.html]
keep_files: [portfolio/_site/contact/index.html]
keep_files: [portfolio/_site/image/]

# Build settings
markdown: kramdown
